<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>voice_nav_audio</name>
  <version>0.1.0</version>
  <description>Local audio and speech processing for VoiceNav Robot</description>
  <maintainer email="983166955@qq.com">Edddddddddy</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>voice_nav_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>action_msgs</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>voice_nav_agent</test_depend>
  <test_depend>voice_nav_bringup</test_depend>
  <test_depend>voice_nav_mission</test_depend>
  <test_depend>voice_nav_sim</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
