<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>voice_nav_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration package for VoiceNav Robot</description>
  <maintainer email="983166955@qq.com">Edddddddddy</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rmw_fastrtps_cpp</exec_depend>
  <exec_depend>voice_nav_agent</exec_depend>
  <exec_depend>voice_nav_audio</exec_depend>
  <exec_depend>voice_nav_mission</exec_depend>
  <exec_depend>voice_nav_sim</exec_depend>

  <test_depend>ament_index_python</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>action_msgs</test_depend>
  <test_depend>geometry_msgs</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>nav_msgs</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>rosgraph_msgs</test_depend>
  <test_depend>sensor_msgs</test_depend>
  <test_depend>tf2_ros_py</test_depend>
  <test_depend>voice_nav_interfaces</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
